"""
Demo script showing how to use the RAG PDF Agent.

This creates a simple test PDF and runs the system.
"""

print("="*80)
print("RAG PDF AGENT - DEMO")
print("="*80)
print()
print("To run the system, you need:")
print("1. A PDF file")
print("2. Python 3.8+")
print("3. Dependencies installed: pip install -r requirements.txt")
print("4. GEMINI_API_KEY environment variable set")
print()
print("="*80)
print("USAGE EXAMPLES")
print("="*80)
print()
print("Basic usage:")
print("  python main.py ./document.pdf")
print()
print("With options:")
print("  python main.py ./report.pdf --model gemini-1.5-flash --top-k 3")
print()
print("Validation:")
print("  python validate.py ./document.pdf")
print()
print("="*80)
print("NEXT STEPS")
print("="*80)
print()
print("1. Get a PDF document to analyze")
print("2. Set your API key:")
print("   $env:GEMINI_API_KEY='your-key-here'")
print("3. Run:")
print("   python main.py ./your_document.pdf")
print()
print("="*80)
